eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

Spring:
  application:
    name: product

server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud?serverTimezone=GMT%2B8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 930223he

